# Generated by Django 2.2.2 on 2019-09-09 14:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_auto_20190909_1427'),
        ('tuition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuition',
            name='lectures',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
        migrations.AddField(
            model_name='tuition',
            name='subject',
            field=models.ManyToManyField(to='tutor.Subject'),
        ),
        migrations.AddField(
            model_name='tuition',
            name='tuition_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('class_number', 'Class Number'), ('instant', 'Instant')], default='monthly', max_length=20),
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('started', 'started'), ('finished', 'finished')], default='started', max_length=20)),
                ('tuition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuition.Tuition')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
