# Generated by Django 2.2.2 on 2019-09-19 04:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0002_auto_20190909_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuition',
            name='lectures',
            field=models.PositiveIntegerField(default=1, help_text='lectures per month', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Student'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='tuition_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('class_number', 'Class Number'), ('instant', 'Instant'), ('contract', 'Contract')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutor.Tutor'),
        ),
    ]
