# Generated by Django 2.2.2 on 2019-11-01 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0009_auto_20191030_1706'),
        ('tuition', '0004_auto_20190919_0646'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestTutor',
            new_name='RequestTuition',
        ),
    ]
