# Generated by Django 2.2.2 on 2019-08-12 04:56

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='invoice_number',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=20, null=True, unique=True),
        ),
    ]
