# Generated by Django 2.2.2 on 2019-08-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190810_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=555, null=True, verbose_name='Full Name of User'),
        ),
    ]
