# Generated by Django 2.2.2 on 2019-09-09 14:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_tutor_verified_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='subject',
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('tuition_type', models.CharField(choices=[('monthly', 'Monthly'), ('class_number', 'Class Number'), ('instant', 'Instant')], default='monthly', max_length=20)),
                ('class_level', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('any', 'Any'), ('class_1', 'Class 1'), ('class_2', 'Class 2'), ('class_3', 'Class 3'), ('class_4', 'Class 4'), ('class_5', 'Class 5'), ('class_6', 'Class 6'), ('class_7', 'Class 7'), ('class_8', 'Class 8'), ('class_9', 'Class 9'), ('class_10', 'Class 10'), ('class_11', 'Class 11'), ('class_12', 'Class 12'), ('o_level', 'O Level'), ('a_level', 'A Level'), ('ba', 'BA'), ('bsc', 'BSc'), ('bcom', 'BCom'), ('masters', 'Masters')], default='any', max_length=25), size=None)),
                ('subject', models.ManyToManyField(to='tutor.Subject')),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tutor.Tutor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tutor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tutor.Department'),
        ),
    ]
