# Generated by Django 2.2.2 on 2019-09-19 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_auto_20190909_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='tuition_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('class_number', 'Class Number'), ('instant', 'Instant'), ('contract', 'Contract')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_verified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
