# Generated by Django 2.2.2 on 2019-10-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_preference_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='college',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='current_institute',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='current_occupation',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='department',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='school',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='university',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='tutor',
            name='nid',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
