# Generated by Django 2.2.2 on 2019-10-10 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile'),
        ('tutor', '0006_auto_20191010_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='user_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
