# Generated by Django 2.2.2 on 2019-10-30 17:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_auto_20191010_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='class_level',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('class_1', 'Class 1'), ('class_2', 'Class 2'), ('class_3', 'Class 3'), ('class_4', 'Class 4'), ('class_5', 'Class 5'), ('class_6', 'Class 6'), ('class_7', 'Class 7'), ('class_8', 'Class 8'), ('class_9', 'Class 9'), ('class_10', 'Class 10'), ('class_11', 'Class 11'), ('class_12', 'Class 12'), ('o_level', 'O Level'), ('a_level', 'A Level'), ('ba', 'BA'), ('bsc', 'BSc'), ('bcom', 'BCom'), ('masters', 'Masters')], default='any', max_length=25), size=None),
        ),
    ]
