# Generated by Django 2.2.2 on 2019-09-09 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('current_institute', models.CharField(blank=True, help_text='current job or service institute.', max_length=255, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tutor.College')),
                ('current_occupation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tutor.Occupation')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tutor.School')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tutor.University')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
