# Generated by Django 2.2.2 on 2019-09-09 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_verified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_verifier', to=settings.AUTH_USER_MODEL),
        ),
    ]
