# Generated by Django 2.2.2 on 2019-10-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190919_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='college',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_institute',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_occupation',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.RemoveField(
            model_name='student',
            name='university',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='student',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
